compatibility_date = "2024-10-04"
main = "src/index.ts"
minify = true
name = "kuma"
upload_source_maps = true
workers_dev = false

[observability]
enabled = true

[assets]
directory = "./dist/"

[[routes]]
pattern = "kuma.chaimi.cc/*"
zone_name = "chaimi.cc"

[build]
command = """
wget https://github.com/louislam/uptime-kuma/releases/latest/download/dist.tar.gz && 
tar -zxvf dist.tar.gz --exclude=*.br --exclude=*.gz  --exclude=dist/icon-512x512.png --exclude=dist/icon-192x192.png --exclude=dist/manifest.json
"""
